# Generated by Django 3.2.3 on 2021-05-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('artisan_basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artisan_basket', to='accounts.userprofile')),
                ('customer_basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_basket', to='accounts.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
