# Generated by Django 3.2.3 on 2021-05-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_artisan',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(default='lskd', max_length=10),
            preserve_default=False,
        ),
    ]
