# Generated by Django 3.2.3 on 2021-05-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210523_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bank_details',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='images/avatar.jpg', upload_to='images'),
        ),
    ]
