# Generated by Django 3.2.3 on 2021-05-24 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='artisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artisanorder', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerorder', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='artisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artisanreview', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerreview', to='accounts.userprofile'),
        ),
    ]
