# Generated by Django 3.2.3 on 2021-05-24 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210524_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='artisan_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artisan_order', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='artisan_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artisan_review', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_review', to='accounts.userprofile'),
        ),
    ]
