# Generated by Django 3.2.3 on 2021-06-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='bicycle_time',
            field=models.CharField(default='1 hour 3mins', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userorder',
            name='driving_time',
            field=models.CharField(default='20 mins', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userorder',
            name='total_distance',
            field=models.CharField(default='35.8', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userorder',
            name='walking_time',
            field=models.CharField(default='2 hours 4 mins', max_length=100),
            preserve_default=False,
        ),
    ]
