# Generated by Django 3.2.3 on 2021-06-10 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_balance'),
        ('order', '0002_auto_20210608_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(max_length=20)),
                ('artisanwithdrawal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artisanwithdrawal', to='accounts.userprofile')),
            ],
        ),
    ]
